### ISSUE TITLE
'symfony console make:migration' doesn't create SQL code

### ISSUE THREAD

**Issue by sputnick-dev** [the-fast-track/book-5.0-1#10]
Hi,

I follow the book, chapter '8.7 Migrer la base de données'.

I have my 2 Entities classes properly generated via `symfony console make:entity` : 

```
ls -1 src/Entity/Co*
src/Entity/Comment.php
src/Entity/Conference.php
```

Ran `symfony console make:migration`, get only : 
```

<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20200322201522 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs

    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE SCHEMA public');
    }
}

```

**Why there's no SQL code generated ?**

My `.env`:

```
APP_ENV=dev
APP_SECRET=xxx
DATABASE_URL=postgresql://127.0.0.1:5432/db?serverVersion=11&charset=utf8`
```

The command `symfony run psql` run well; I get psql prompt

```
symfony -V
Symfony CLI version v4.13.3 (Thu Mar 19 15:24:08 UTC 2020)
```

```
php bin/console debug:container --env-vars

Symfony Container Environment Variables
=======================================

 -------------- --------------- ---------------------------------------------------------------- 
  Name           Default value   Real value                                                      
 -------------- --------------- ---------------------------------------------------------------- 
  APP_SECRET     n/a             "4ec3efda62f1b3001e78459335893c3f"                              
  DATABASE_URL   n/a             "postgresql://127.0.0.1:5432/db?serverVersion=11&charset=utf8"  
 -------------- --------------- ---------------------------------------------------------------- 

 // Note real values might be different between web and CLI. 
```

Never edited Symfony config :
```
cat config/packages/doctrine.yaml
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
```
